# # Base application routes
helpdesk_member_application_base:
    path:     /
    controller: Webkul\UVDesk\AppBundle\Controller\Application::renderApplicationList

helpdesk_member_install_application_xhr:
    path:     /install
    controller: Webkul\UVDesk\AppBundle\Controller\Application::installXhr

helpdesk_member_uninstall_application_xhr:
    path:     /uninstall
    controller: Webkul\UVDesk\AppBundle\Controller\Application::uninstallXhr

# app load route , keep this at end of file
helpdesk_member_load_application:
    path:     /{applicationRouteName}/{activeTab}
    controller: Webkul\UVDesk\AppBundle\Controller\Application::loadApplication
    defaults: { panelId: 'apps', activeTab: '' }

# app_list_xhr:
#     path:     /xhr
#     defaults: { _controller: WebkulAppBundle:Application:listXhr }

# development routes
helpdesk_member_load_application_shopify:
    path:     /shopify
    controller: Webkul\UVDesk\AppBundle\Controller\Application::loadApplication
    defaults: { panelId: 'apps' }

helpdesk_member_load_application_eBay:
    path:     /eBay
    controller: Webkul\UVDesk\AppBundle\Controller\Application::loadApplication
    defaults: { panelId: 'apps' }

app_enable_xhr:
    path:     /enable
    controller: Webkul\UVDesk\AppBundle\Controller\Application::enableXhr

app_save_application_channel:
    path:     /{applicationRouteName}/channel/save/{channelId}
    controller: Webkul\UVDesk\AppBundle\Controller\Application::createApplicationChannel
    defaults: { channelId: 0 }
    requirements:
        channelId: '\d+'

app_save_application_settings:
    path:     /{applicationRouteName}/channel/save/settings/{channelId}
    defaults: { _controller: WebkulAppBundle:Application:saveApplicationChannelSetting, channelId: 0 }
    requirements:
        channelId: '\d+'

app_remove_application_channel:
    path:     /shopify/channel/remove/{channelId}
    controller: Webkul\UVDesk\AppBundle\Controller\Application::removeApplicationChannel
    defaults: { channelId: 0 }
    requirements:
        channelId: '\d+'

app_fetch_application_collection:
    path:     /{applicationRouteName}/collection/fetch
    controller: Webkul\UVDesk\AppBundle\Controller\Application::getApplicationChannelCollectionXhr

app_process_application_external_redirect:
    path:     /{applicationRouteName}/handle/redirect
    controller: Webkul\UVDesk\AppBundle\Controller\Application::applicationExternalRedirect

app_application_medium:
    path:     /{applicationRouteName}/medium/{apiEndpoint}
    defaults: { _controller: WebkulAppBundle:Application:applicationAPIEndpoint }

# # Application Routes
# app_route_ecommerce:
#     resource: "@WebkulAppBundle/Resources/config/route/ecommerce.yml"
#     prefix:   /

# customer_tickets_xhr:
#     path:   /customer-tickets/xhr
#     defaults: { _controller: WebkulAppBundle:Application:customerTicketsXhr }

# search_company_articles:
#     path:   /articles/search
#     defaults: { _controller: WebkulAppBundle:Application:searchCompanyArticles }

# app_google_calendar_xhr:
#     path:   /google-calendar/{incrementId}/xhr
#     defaults: { _controller: WebkulAppBundle:Application:customApiXhr }

# app_google_calendar_edit_xhr:
#     path:   /google-calendar/{incrementId}/xhr/{eventId}
#     defaults: { _controller: WebkulAppBundle:Application:customApiXhr }
#     methods: [PUT, DELETE]

# app_new_features_xhr:
#     path:     /new-features
#     defaults: { _controller: WebkulAppBundle:NewFeature:newFeaturesXhr, activeTab: '' }

# app_data_xhr:
#     path:     /{applicationRouteName}/xhr
#     defaults: { _controller: WebkulAppBundle:Application:getAppData }

# # app load route , keep this at end of file
# app_load_application:
#     path:     /{applicationRouteName}/{activeTab}
#     defaults: { _controller: WebkulAppBundle:Application:loadApplication, activeTab: '' }

# # test_test_test:
# #     path:     /testtest/{applicationRouteName}
# #     defaults: { _controller: WebkulAppBundle:Application:applicationBackgroundProcess }
