services:
    application.service:
        public: true
        class: Webkul\UVDesk\CoreBundle\Services\ApplicationService
        arguments: ['@service_container', '@request_stack', '@doctrine.orm.entity_manager']
